# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likers', models.ManyToManyField(related_name='likedquote', to='exam_app.User')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedquote', to='exam_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='likers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
