# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='readers',
            new_name='likers',
        ),
    ]
