# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20180702_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
