# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('added_by', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
                ('action', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('others_wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others_wish_list', to='Exam_app.User')),
                ('users_wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wish_list', to='Exam_app.User')),
            ],
        ),
    ]
