# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0004_auto_20180627_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
