# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20180628_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='quoter',
            new_name='poster',
        ),
        migrations.AddField(
            model_name='list',
            name='author',
            field=models.CharField(default='blah', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='likes',
            field=models.ManyToManyField(related_name='my_likes', to='exam_app.User'),
        ),
    ]
