# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20180628_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='likes',
        ),
        migrations.AddField(
            model_name='list',
            name='favorites',
            field=models.ManyToManyField(related_name='my_faves', to='exam_app.User'),
        ),
    ]
