# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_user_joins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='users',
        ),
    ]
