# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other',
            name='add_friend',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
    ]
