# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 19:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0002_wish'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wish',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
