# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0003_auto_20180627_1552'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wish',
            managers=[
            ],
        ),
    ]
