# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0005_auto_20180627_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='others_wish',
        ),
        migrations.AddField(
            model_name='wish',
            name='others_wish',
            field=models.ManyToManyField(related_name='joined_trips', to='Exam_app.User'),
        ),
    ]
