# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0006_auto_20180627_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='others_wish',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='users_wish',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
