# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0008_wish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='joiner',
            new_name='joiners',
        ),
    ]
