# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likesbook_app', '0003_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='readers',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
