# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='joiners',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='list',
            name='quoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_quotes', to='exam_app.User'),
        ),
    ]
