# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_auto_20180628_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='list',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(related_name='person', to='exam_app.User'),
        ),
    ]
