# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180619_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='join',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
