# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_actor_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='myapp.Movie')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='myapp.Actor')),
            ],
        ),
    ]
